spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testcontainers
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: classpath:com.iskrypnik.testcontainers.db/changelog-master.yaml